### ISSUE TITLE
Error when using with Next.js

### ISSUE THREAD

**Issue by sebpowell** [airbnb/visx#1679] opened 2023-03-26 20:05 UTC
I'm trying to use this library with Next.js (13.2.1), but get the following error when I try copying the example found here (https://airbnb.io/visx/barstack).

```
Error: require() of ES Module /node_modules/d3-scale/src/index.js from /node_modules/@visx/scale/lib/scales/band.js not supported. Instead change the require of index.js in /node_modules/@visx/scale/lib/scales/band.js to a dynamic import() which is available in all CommonJS modules.
```
Removing all calls to `scaleBand` allows the page to load, but the chart doesn't work as it should. I also tried doing a dynamic import as suggested, but that didn't work either. 

Any ideas? I'm using visx 3.1.2.

**Comment by williaster** [comment] 2023-03-26 23:28
hey @sebpowell thanks for taking the time to create an issue. going to close as a duplicate of https://github.com/airbnb/visx/issues/1637 where there are some work arounds suggested. still trying to get resolution on for a fix, for now you can downgrade to `2.X` versions of the packages.

**Closed by williaster** 2023-03-26 23:28 UTC

**Comment by sebpowell** [comment] 2023-03-27 06:59
@williaster – thank you! Apologies, I didn't see the other thread. Will check it out today, thank you for replying.
