### ISSUE TITLE
help: glyph is being clipped by the vertical and horizontal crosshair

### ISSUE THREAD

**Issue by myronlopes-tuks** [airbnb/visx#1337] opened 2021-09-06 12:09 UTC
Hi

What i am trying to do: Just to display the tooltip glyph similiar to the vxDemo [here](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-xychart?file=/ExampleControls.tsx).

My glyph is _clipping_ around the horizontal and vertical crosshairs: [Looks like this](https://imgur.com/a/rowv5RX)

Expected: [like this](https://imgur.com/WtniCuZ)

**My code:**

```jsx
 <Tooltip
                    snapTooltipToDatumX
                    showVerticalCrosshair
                    showDatumGlyph
                    glyphStyle={({
                        r: 20,
                        className: 'clipped-glyph',
                        id: 'this-frustrating-glyph'
                    })}
                    renderTooltip={({
                        tooltipData,
                        colorScale,
                    }) => (
                        <div>
                            {/*First Line*/}
                            <div
                                style={{
                                    color: props.tooltipKeyColor
                                }}
                            >
                                {Object.keys(tooltipData.datumByKey)[0]}
                                {': '}
                            </div>
                            {
                                tooltipData.datumByKey.Line1 === null || tooltipData.datumByKey.Line1 === undefined
                                    ? '–'
                                    : tooltipData.datumByKey.Line1.datum.y
                            }   
                  }
            >                      
   ```
   
I suspect this is perhaps some CSS issue? 
I have tried setting `position:absolute` as well `z-index: 9999...` but the glyph remained clipped.
I haven't added or changed any of the css of the crosshairs or anything either.
   
   any help would be appreciate.

**Comment by williaster** [comment] 2021-09-07 18:59
Hi @myronlopes-tuks 👋  Can you share a sandbox that reproduced this issue? I tried setting `glyphStyle={{ r: 20 }}` myself and it worked fine [here](https://codesandbox.io/s/gracious-solomon-w1wem?file=/Example.tsx) / I can't reproduce it.

![image](https://user-images.githubusercontent.com/4496521/132396939-61f6804f-922c-4644-b383-b7bd4d3941f2.png)

**Comment by hshoff** [comment] 2022-01-03 22:24
Closing for now. Feel free to reopen

**Closed by hshoff** 2022-01-03 22:24 UTC
Labels: @visx/xychart

**Comment by mtholdefer** [comment] 2022-01-20 20:42
I am also experiencing this issue. 

![image](https://user-images.githubusercontent.com/4721771/150418829-c16e8564-4ae2-4f23-879d-948cfb41ab63.png)
 
I will try to get it to reproduce in a sandbox

**Comment by vorillaz** [comment] 2022-02-09 21:47
@mtholdefer @hshoff Sorry to bother you with a comment but I spotted the culprit on this one, in my case I had a global CSS rule coming from `reset.css`:
```css
  svg:not(:root) {
    overflow: hidden;
  }
```
