### ISSUE TITLE
Unable to compile Zoom 

### ISSUE THREAD

**Issue by sadudani** [airbnb/visx#1284] opened 2021-07-21 14:14 UTC
I'm getting the following error. I'm just using the provided example demo-
![zoomIssue](https://user-images.githubusercontent.com/44669773/126503485-bbbe1bec-298d-43ce-9ac2-adb707e14422.PNG)
zoom-i

JSX element class does not support attributes because it does not have a 'props' property.ts(2607)
'Zoom' cannot be used as a JSX component.
  Its instance type 'Zoom' is not a valid JSX element.
    Type 'Zoom' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refsts(2786)
(alias) class Zoom
import Zoom

**Comment by williaster** [comment] 2021-07-21 20:49
Hey @sadudani  👋  thanks for checking out `visx`. Just to verify, you are importing `Zoom` via the named import `import { Zoom } from '@visx/zoom';` not the default import `import Zoom from '@visx/zoom';`?

If that doesn't work I'd guess there is some type of TS config error but that's hard to debug without a sandbox of your env, and the [codesandbox of zoom-i](https://codesandbox.io/s/github/airbnb/visx/tree/master/packages/visx-demo/src/sandboxes/visx-zoom-i?file=/Example.tsx) works just fine.

**Comment by sadudani** [comment] 2021-07-22 14:19
We are tring to reproduce the zoom-i example. We are using
 import { Zoom } from '@visx/zoom';
The tsconfig file is also compatible as the zoom-i. What do you think could be the issue?

**Comment by williaster** [comment] 2021-07-22 19:24
Sorry, it's going to be difficult to debug this unless you can fully reproduce it in a codesandbox since it clearly works in our demo codesandbox. Your app could have any number of issues.

**Comment by hshoff** [comment] 2024-03-23 14:24
Closing for now. Happy to reopen with more information or if someone else encounters this.

**Closed by hshoff** 2024-03-23 14:24 UTC
Labels: 🔮 question, @visx/zoom
