### ISSUE TITLE
does visx/geo support GeoJSON ?

### ISSUE THREAD

**Issue by kid1412621** [airbnb/visx#858] opened 2020-10-08 14:05 UTC
all examples are written in TopoJSON. wondering how to use with geojson directly. after all TopoJSON-client is another layer of complixity I don't wanna add to my project.

much more detailed docs will be grateful.

**Comment by kid1412621** [comment] 2020-10-08 14:51
actually I'm fellowing [this demo](https://airbnb.io/visx/geo-mercator), and using [this map data](https://github.com/deldersveld/topojson/blob/master/countries/china/china-provinces-simplified.json), but I got this error: 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/26278054/95475279-a1e98400-09b8-11eb-87e4-05c335b8f4b9.png">

help, plz

**Comment by williaster** [comment] 2020-10-20 20:02
Hey @kid1412621 thanks for checking out `visx`. `visx` uses `d3-geo` for projections and path generators, and since `d3-geo` expects `GeoJSON` as input, yes it is supported. We use `TopoJSON` in the examples because of the significantly smaller file size for the hosted map data.

As the docs specify, `Projection`s expect the input `data: Datum[]` to be an array of `GeoJson` features or geometry objects. These are then [parsed one by one by the `d3.geoPath`](https://github.com/airbnb/visx/blob/master/packages/visx-geo/src/projections/Projection.tsx#L158). 

I couldn't get your dataset to render quickly, but was able to render a similar GeoJson object [here](https://codesandbox.io/s/sleepy-shockley-furi3?file=/Example.tsx) using [this dataset](https://github.com/waylau/svg-china-map/blob/master/china-map/china.geo.json). Going to close this for now, feel free to re-open if you have further problems or questions. Hope that helps!

<img src="https://user-images.githubusercontent.com/4496521/96638070-7168ea80-12d4-11eb-897c-c6019e8e5649.png" width="400" />

**Closed by williaster** 2020-10-20 20:02 UTC
Labels: @visx/geo, 🐯example, 🔮question

**Comment by kid1412621** [comment] 2020-10-21 14:42
@williaster thank! you guy so nice, I've tried your demo, it's fine for me too. But after copied code(include the dataset) into my project, it still shows the same error. I even deleted all the dependencies and reinstalled them to match the version in the demo. If any info I can offer, just name it.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/26278054/96734541-3dcdb380-13ed-11eb-8ba9-d12a5834e572.png">

**Comment by williaster** [comment] 2020-10-21 22:35
hmm, it's tricky to debug further without a codesandbox link or equivalent. can you reproduce it in an environment like that?

**Comment by kid1412621** [comment] 2020-10-22 14:17
> hmm, it's tricky to debug further without a codesandbox link or equivalent. can you reproduce it in an environment like that?

I upload to a [temp repo](https://github.com/kid1412621/visx-geo-demo), hopefully I didn't do something stupid.😂

**Comment by williaster** [comment] 2020-10-22 18:06
Looks like you [render `Area` without setting any `width/height`](https://github.com/kid1412621/visx-geo-demo/blob/main/src/App.js#L9) which means the projection is using `undefined` in all of its calculations which probably results in `NaN`s.

**Comment by kid1412621** [comment] 2020-10-24 09:46
> Looks like you [render `Area` without setting any `width/height`](https://github.com/kid1412621/visx-geo-demo/blob/main/src/App.js#L9) which means the projection is using `undefined` in all of its calculations which probably results in `NaN`s.

What an idiot I was,😩 thanks again!
