### ISSUE TITLE
'Tooltip' cannot be used as a JSX component 

### ISSUE THREAD

**Issue by V-iktor** [airbnb/visx#1755] opened 2023-09-30 14:01 UTC
I am attempting to recreate this in a Next 13 App Router but get the following error

https://airbnb.io/visx/areas

```
'Tooltip' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<TooltipProps & HTMLAttributes<HTMLDivElement> & RefAttributes<HTMLDivElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<TooltipProps & HTMLAttributes<HTMLDivElement> & RefAttributes<HTMLDivElement>>' is not assignable to type '(props: any, deprecatedLegacyContext?: any) => ReactNode'.
      Type 'import(".../node_modules/@types/react-dom/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.ts(2786)
```

### package.json

```
    "@types/node": "20.3.1",
    "@types/react": "18.2.12",
    "@types/react-dom": "18.2.5",

    "@visx/curve": "^3.3.0",
    "@visx/event": "^3.3.0",
    "@visx/gradient": "^3.3.0",
    "@visx/grid": "^3.3.0",
    "@visx/mock-data": "^3.3.0",
    "@visx/scale": "^3.3.0",
    "@visx/shape": "^3.3.0",
    "@visx/tooltip": "^3.3.0",

    "react": "18.2.0",
    "react-dom": "18.2.0",
```

**Comment by behzadam** [comment] 2023-10-02 10:19
I have same issue: [source](https://github.com/behzadam/linkka)

**Comment by williaster** [comment] 2023-10-31 17:19
Hmm, seems like a type issue/type mismatch potentially. Unless you can fully recreate this in a sandbox I'm not sure we can really debug.

**Comment by williaster** [comment] 2023-12-15 21:11
again looks like a type mismatch to me. closing for now without a reproducible example

**Closed by williaster** 2023-12-15 21:11 UTC
Labels: @visx/tooltip
