### ISSUE TITLE
Snowpack flags this warning - Non-existent export TextProps from esm/types.js

### ISSUE THREAD

**Issue by httpete** [airbnb/visx#1335] opened 2021-09-02 21:42 UTC
[esinstall] /home/myhome/git/snow/node_modules/@visx/text/esm/Text.js:7:9 Non-existent export 'TextProps' is imported from node_modules/@visx/text/esm/types.js

**Comment by hshoff** [comment] 2022-01-03 22:04
Duplicate of https://github.com/airbnb/visx/issues/1344. Will merge into one issue for tracking.

**Closed by hshoff** 2022-01-03 22:04 UTC
